changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: Bugs Fixes
      labels:
        - bug
    - title: Features
      labels:
        - enhancement
    - title: Other Changes
      labels:
        - "*"
